# Generated by Django 4.2.6 on 2024-01-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productvariant_max_price_and_more'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_name',
            field=models.CharField(default='my wishlist', max_length=200),
        ),
    ]
