# Generated by Django 4.2.6 on 2023-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled by Admin', 'Cancelled by Admin'), ('Cancelled by User', 'Cancelled by User'), ('Returned', 'Returned')], default='Order placed', max_length=20),
        ),
    ]
