# Generated by Django 4.2.6 on 2023-11-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
    ]
