# Generated by Django 4.2.6 on 2024-02-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReturnReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_return_reason', models.CharField(choices=[('Wrong product ordered', 'Wrong product ordered'), ('Product is not required anymore.', 'Product is not required anymore.'), ('The product was damaged or defective.', 'The product was damaged or defective.'), ('The quality of product was cheap', 'The quality of product was cheap'), ('The product arrived late ', 'The product arrived late'), (' Wrong product shipped', 'Wrong product shipped'), ('Wardrobing', 'Wardrobing'), ('other', 'other')], default='Select a reason', max_length=500)),
                ('others', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_order_reason', models.CharField(choices=[(' I have bought the wrong item', ' I have bought the wrong item'), ('I have found a cheaper alternative for lesser price.', 'I have found a cheaper alternative for lesser price.'), ('I have provided the wrong address.', 'I have provided the wrong address.'), ('Expected delivery date has changed and the product is arriving at a later date.', 'Expected delivery date has changed and the product is arriving at a later date.'), ('Product is not required anymore.', 'Product is not required anymore.'), ('Bad review from friends/relatives after ordering the product.', 'Bad review from friends/relatives after ordering the product.'), ('Product is taking too long to be delivered', ' Product is taking too long to be delivered'), ('other', 'other')], default='Select a reason', max_length=500)),
                ('others', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
