# Generated by Django 4.2.6 on 2024-02-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_cancellationreasons_orderproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationreasons',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cancellationreasons',
            name='orderProduct',
        ),
        migrations.RemoveField(
            model_name='returnreasons',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returnreasons',
            name='orderProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='full_cancellation_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cancellationreasons'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_cancellation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='full_return_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.returnreasons'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cancellationreasons'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled by Admin', 'Cancelled by Admin'), ('Cancelled by User', 'Cancelled by User'), ('Returned', 'Returned')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='return_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.returnreasons'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
