# Generated by Django 4.2.6 on 2024-02-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_cancellationreasons_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationreasons',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnreasons',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
