# Generated by Django 4.2.6 on 2024-02-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_cancellationreasons_others_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cancellationreasons'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='return_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.returnreasons'),
        ),
    ]
