# Generated by Django 4.2.6 on 2024-02-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_orderproduct_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_descripition',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
