# Generated by Django 4.2.6 on 2024-02-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_payment_error_descripition_payment_error_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='error_descripition',
            new_name='error_description',
        ),
    ]
