# Generated by Django 4.2.6 on 2024-02-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_cancellation_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_return_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_return_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='others',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_requested',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='cancellation_requested',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='return_requested',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Payment Pending', 'Payment Pending'), ('Cancellation Requested', 'Cancellation Requested'), ('Full Cancellation Requested', 'Full Cancellation Requested'), ('Return Requested', 'Return Requested'), ('Full Return Requested', 'Full Return Requested')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Cancellation Requested', 'Cancellation Requested'), ('Return Requested', 'Return Requested')], default='New', max_length=100),
        ),
    ]
