# Generated by Django 4.2.6 on 2024-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_cancellation_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Partially Cancelled', 'Partially Cancelled'), ('Returned', 'Returned'), ('Cancellation Requested', 'Cancellation Requested'), ('Return Requested', 'Return Requested')], default='New', max_length=100),
        ),
    ]
