# Generated by Django 4.2.6 on 2024-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_orderproduct_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Partially Cancelled', 'Partially Cancelled'), ('Returned', 'Returned'), ('Partially Returned', 'Partially Returned'), ('Payment Pending', 'Payment Pending'), ('Cancellation Requested', 'Cancellation Requested'), ('Return Requested', 'Return Requested')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Cancellation Requested', 'Cancellation Requested'), ('Return Requested', 'Return Requested')], default='New', max_length=100),
        ),
    ]
