# Generated by Django 4.2.6 on 2024-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Cancellation Requested', 'Cancellation Requested'), ('Cancellation Rejected', 'Cancellation Rejected'), ('Return Requested', 'Return Requested'), ('Return Rejected', 'Return Rejected')], default='New', max_length=100),
        ),
    ]
