# Generated by Django 4.2.6 on 2024-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_orderproduct_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Payment Pending', 'Payment Pending'), ('Partially Cancelled', 'Partially Cancelled'), ('Partially Returned', 'Partially Returned'), ('Completed', 'Completed'), ('Cancel or Return Requested', 'Cancel or Return Requested')], default='New', max_length=100),
        ),
    ]
