# Generated by Django 4.2.6 on 2024-02-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_email_alter_account_phone_number'),
        ('order', '0028_order_coupon_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.addresses'),
        ),
    ]
