# Generated by Django 4.2.6 on 2024-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
                ('minimum_amount', models.IntegerField(default=200)),
                ('description', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
