# Generated by Django 4.2.6 on 2024-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=200),
        ),
    ]
