# Generated by Django 4.2.6 on 2023-11-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_userprofile_addresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
