# Generated by Django 4.2.6 on 2023-12-05 07:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
