# Generated by Django 4.2.6 on 2024-02-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productvariant_max_price_and_more'),
        ('cart', '0004_cart_item_user_alter_cart_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
    ]
