# Generated by Django 4.2.6 on 2023-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
